--------------------------------------------------------
--  파일이 생성됨 - 일요일-3월-28-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_ALARM_NO
--------------------------------------------------------

   CREATE SEQUENCE  "SPARKLING"."SEQ_ALARM_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 60 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BBUY_NO
--------------------------------------------------------

   CREATE SEQUENCE  "SPARKLING"."SEQ_BBUY_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BOOKING_NO
--------------------------------------------------------

   CREATE SEQUENCE  "SPARKLING"."SEQ_BOOKING_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 7 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BUYPROD_NO
--------------------------------------------------------

   CREATE SEQUENCE  "SPARKLING"."SEQ_BUYPROD_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 70 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BUY_NO
--------------------------------------------------------

   CREATE SEQUENCE  "SPARKLING"."SEQ_BUY_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 25 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CART_NO
--------------------------------------------------------

   CREATE SEQUENCE  "SPARKLING"."SEQ_CART_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_COLORSIZE_NO
--------------------------------------------------------

   CREATE SEQUENCE  "SPARKLING"."SEQ_COLORSIZE_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 17 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CON_NO
--------------------------------------------------------

   CREATE SEQUENCE  "SPARKLING"."SEQ_CON_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 12 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_EVENT_NO
--------------------------------------------------------

   CREATE SEQUENCE  "SPARKLING"."SEQ_EVENT_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_GYMIMG_NO
--------------------------------------------------------

   CREATE SEQUENCE  "SPARKLING"."SEQ_GYMIMG_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 12 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_GYM_NO
--------------------------------------------------------

   CREATE SEQUENCE  "SPARKLING"."SEQ_GYM_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MATCHSCORE_NO
--------------------------------------------------------

   CREATE SEQUENCE  "SPARKLING"."SEQ_MATCHSCORE_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PROD_IMG_NO
--------------------------------------------------------

   CREATE SEQUENCE  "SPARKLING"."SEQ_PROD_IMG_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PROD_NO
--------------------------------------------------------

   CREATE SEQUENCE  "SPARKLING"."SEQ_PROD_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 8 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PROFILE_NO
--------------------------------------------------------

   CREATE SEQUENCE  "SPARKLING"."SEQ_PROFILE_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PROFIT_NO
--------------------------------------------------------

   CREATE SEQUENCE  "SPARKLING"."SEQ_PROFIT_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_QNA_IMG_NO
--------------------------------------------------------

   CREATE SEQUENCE  "SPARKLING"."SEQ_QNA_IMG_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_QNA_NO
--------------------------------------------------------

   CREATE SEQUENCE  "SPARKLING"."SEQ_QNA_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_RECORD_NO
--------------------------------------------------------

   CREATE SEQUENCE  "SPARKLING"."SEQ_RECORD_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_REVIEW_IMG_NO
--------------------------------------------------------

   CREATE SEQUENCE  "SPARKLING"."SEQ_REVIEW_IMG_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_REVIEW_NO
--------------------------------------------------------

   CREATE SEQUENCE  "SPARKLING"."SEQ_REVIEW_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SELL_NO
--------------------------------------------------------

   CREATE SEQUENCE  "SPARKLING"."SEQ_SELL_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 13 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_USER_NO
--------------------------------------------------------

   CREATE SEQUENCE  "SPARKLING"."SEQ_USER_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ALARM
--------------------------------------------------------

  CREATE TABLE "SPARKLING"."ALARM" 
   (	"ALARM_NO" NUMBER, 
	"FROM_USER_NO" NUMBER, 
	"TO_USER_NO" NUMBER, 
	"ALARM_CONTENT" VARCHAR2(3000 BYTE), 
	"ALARM_DATE" DATE, 
	"SELL_NO" NUMBER, 
	"ALARM_TITLE" VARCHAR2(500 BYTE), 
	"BUY_TYPE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BBUY
--------------------------------------------------------

  CREATE TABLE "SPARKLING"."BBUY" 
   (	"B_BUY_NO" NUMBER, 
	"USER_NO" NUMBER, 
	"BOOKING_NO" NUMBER, 
	"PROFILE_NO" NUMBER, 
	"B_BUY_PAYTYPE" VARCHAR2(200 BYTE), 
	"B_BUY_PRICE" NUMBER, 
	"B_BUY_STATE" VARCHAR2(200 BYTE), 
	"B_BUY_PLAYER_STATE" VARCHAR2(200 BYTE), 
	"B_BUY_DATE" DATE, 
	"B_BUY_ADDRESS" VARCHAR2(200 BYTE), 
	"B_BUY_DAY" VARCHAR2(200 BYTE), 
	"B_BUY_TIME" VARCHAR2(200 BYTE), 
	"B_BUY_EVENT" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BOOKING
--------------------------------------------------------

  CREATE TABLE "SPARKLING"."BOOKING" 
   (	"BOOKING_NO" NUMBER, 
	"GYM_NO" NUMBER, 
	"BOOKING_DATE" VARCHAR2(200 BYTE), 
	"BOOKING_START" VARCHAR2(200 BYTE), 
	"BOOKING_END" VARCHAR2(200 BYTE), 
	"BOOKING_PRICE" NUMBER, 
	"BOOKING_STATE" VARCHAR2(200 BYTE), 
	"BOOKING_REG_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BUY
--------------------------------------------------------

  CREATE TABLE "SPARKLING"."BUY" 
   (	"BUY_NO" NUMBER, 
	"USER_NO" NUMBER, 
	"BUY_ADDRESS" VARCHAR2(300 BYTE), 
	"BUY_PH" NUMBER, 
	"BUY_DATE" DATE, 
	"BUY_PAYTYPE" VARCHAR2(200 BYTE), 
	"BUY_PRICE" NUMBER, 
	"BUY_STATE" VARCHAR2(200 BYTE), 
	"BUY_NAME" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BUYPRODUCT
--------------------------------------------------------

  CREATE TABLE "SPARKLING"."BUYPRODUCT" 
   (	"BUYPROD_NO" NUMBER, 
	"PROD_NO" VARCHAR2(200 BYTE), 
	"COLORSIZE_NO" NUMBER, 
	"BUY_DEL_NO" NUMBER, 
	"BUY_DELIVERY" VARCHAR2(300 BYTE), 
	"BUY_DEL_STATE" VARCHAR2(300 BYTE), 
	"COUNT" NUMBER, 
	"BUY_NO" NUMBER, 
	"BUYPROD_PRICE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CART
--------------------------------------------------------

  CREATE TABLE "SPARKLING"."CART" 
   (	"CART_NO" NUMBER, 
	"USER_NO" NUMBER, 
	"PROD_NO" VARCHAR2(200 BYTE), 
	"COLORSIZE_NO" NUMBER, 
	"COUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COLORSIZE
--------------------------------------------------------

  CREATE TABLE "SPARKLING"."COLORSIZE" 
   (	"COLORSIZE_NO" NUMBER, 
	"PROD_NO" VARCHAR2(200 BYTE), 
	"PROD_SIZE" VARCHAR2(500 BYTE), 
	"COLOR" VARCHAR2(500 BYTE), 
	"STOCK" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONVENIENCE
--------------------------------------------------------

  CREATE TABLE "SPARKLING"."CONVENIENCE" 
   (	"CON_NO" NUMBER, 
	"GYM_NO" NUMBER, 
	"CON_NAME" VARCHAR2(200 BYTE), 
	"CON_STATE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EVENT
--------------------------------------------------------

  CREATE TABLE "SPARKLING"."EVENT" 
   (	"EVENT_NO" NUMBER, 
	"PROFILE_NO" NUMBER, 
	"EVENT_NAME" NUMBER, 
	"CLASS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GYM
--------------------------------------------------------

  CREATE TABLE "SPARKLING"."GYM" 
   (	"GYM_NO" NUMBER, 
	"SELL_NO" NUMBER, 
	"GYM_NAME" VARCHAR2(200 BYTE), 
	"GYM_ADDRESS" VARCHAR2(300 BYTE), 
	"GYM_PH" VARCHAR2(200 BYTE), 
	"GYM_TIME" VARCHAR2(300 BYTE), 
	"GYM_NOTICE" VARCHAR2(4000 BYTE), 
	"GYM_EVENT" VARCHAR2(50 BYTE), 
	"GYM_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GYMIMG
--------------------------------------------------------

  CREATE TABLE "SPARKLING"."GYMIMG" 
   (	"GYM_IMG_NO" NUMBER, 
	"GYM_NO" NUMBER, 
	"GYM_IMG_SAVENAME" VARCHAR2(500 BYTE), 
	"GYM_IMG_NAME" VARCHAR2(500 BYTE), 
	"GYM_IMG_TYPE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MATCHSCORE
--------------------------------------------------------

  CREATE TABLE "SPARKLING"."MATCHSCORE" 
   (	"MATCHSCORE_NO" NUMBER, 
	"USER_NO" NUMBER, 
	"SCORE" NUMBER, 
	"WIN" NUMBER, 
	"LOSE" NUMBER, 
	"B_BUY_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODIMG
--------------------------------------------------------

  CREATE TABLE "SPARKLING"."PRODIMG" 
   (	"PROD_IMG_NO" NUMBER, 
	"PROD_NO" VARCHAR2(200 BYTE), 
	"PROD_IMG_NAME" VARCHAR2(1000 BYTE), 
	"PROD_IMG_SAVENAME" VARCHAR2(1000 BYTE), 
	"PROD_IMG_TYPE" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "SPARKLING"."PRODUCT" 
   (	"PROD_NO" VARCHAR2(200 BYTE), 
	"SELL_NO" NUMBER, 
	"PROD_CATE" VARCHAR2(200 BYTE), 
	"EVENT_CATE" VARCHAR2(500 BYTE), 
	"PROD_NAME" VARCHAR2(500 BYTE), 
	"PROD_PRICE" NUMBER, 
	"PROD_BRAND" VARCHAR2(200 BYTE), 
	"PROD_DESC" VARCHAR2(2000 BYTE), 
	"PROD_FROM" VARCHAR2(2000 BYTE), 
	"PROD_WASH" VARCHAR2(2000 BYTE), 
	"PROD_QUAL" VARCHAR2(2000 BYTE), 
	"PROD_DETAIL" VARCHAR2(2000 BYTE), 
	"PROD_DETAIL_IMG_NAME" VARCHAR2(1000 BYTE), 
	"PROD_DETAIL_IMG_SAVENAME" VARCHAR2(1000 BYTE), 
	"PROD_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROFILE
--------------------------------------------------------

  CREATE TABLE "SPARKLING"."PROFILE" 
   (	"PROFILE_NO" NUMBER, 
	"USER_NO" NUMBER, 
	"HEIGHT" NUMBER, 
	"WEIGHT" NUMBER, 
	"CAREER" VARCHAR2(50 BYTE), 
	"MAJOR" VARCHAR2(300 BYTE), 
	"EXP" NUMBER, 
	"PROFILE_DATE" DATE, 
	"RECENTLY_EXER" VARCHAR2(200 BYTE), 
	"WORD" VARCHAR2(500 BYTE), 
	"PROFILE_GYM_EVENT" VARCHAR2(100 BYTE), 
	"DAY" VARCHAR2(50 BYTE), 
	"TIME" VARCHAR2(200 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table QNA
--------------------------------------------------------

  CREATE TABLE "SPARKLING"."QNA" 
   (	"QNA_NO" NUMBER, 
	"PROD_NO" VARCHAR2(200 BYTE), 
	"QNA_TITLE" VARCHAR2(1000 BYTE), 
	"QNA_CONTENT" VARCHAR2(3000 BYTE), 
	"QNA_DATE" DATE, 
	"QNA_TYPE" VARCHAR2(200 BYTE), 
	"USER_NO" NUMBER, 
	"BUY_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table QNAIMG
--------------------------------------------------------

  CREATE TABLE "SPARKLING"."QNAIMG" 
   (	"QNA_IMG_NO" NUMBER, 
	"QNA_NO" NUMBER, 
	"QNA_IMG_NAME" VARCHAR2(1000 BYTE), 
	"QNA_IMG_SAVENAME" VARCHAR2(1000 BYTE), 
	"QNA_IMG_TYPE" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECORD
--------------------------------------------------------

  CREATE TABLE "SPARKLING"."RECORD" 
   (	"RECORD_NO" NUMBER, 
	"PROFILE_NO" NUMBER, 
	"RECORD_TYPE" VARCHAR2(300 BYTE), 
	"RECORD_NAME" VARCHAR2(300 BYTE), 
	"RECORD_EVENT" VARCHAR2(300 BYTE), 
	"RECORD_DATE" DATE, 
	"RECORD_MATCH" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REVIEW
--------------------------------------------------------

  CREATE TABLE "SPARKLING"."REVIEW" 
   (	"REVIEW_NO" NUMBER, 
	"PROD_NO" VARCHAR2(200 BYTE), 
	"REVIEW_TITLE" VARCHAR2(1000 BYTE), 
	"REVIEW_CONTENT" VARCHAR2(3000 BYTE), 
	"REVIEW_DATE" DATE, 
	"BUY_NO" NUMBER, 
	"USER_NO" NUMBER, 
	"REVIEW_HIT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REVIEWIMG
--------------------------------------------------------

  CREATE TABLE "SPARKLING"."REVIEWIMG" 
   (	"REVIEW_IMG_NO" NUMBER, 
	"REVIEW_NO" NUMBER, 
	"REVIEW_IMG_NAME" VARCHAR2(1000 BYTE), 
	"REVIEW_IMG_SAVENAME" VARCHAR2(1000 BYTE), 
	"REVIEW_IMG_TYPE" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SELLER
--------------------------------------------------------

  CREATE TABLE "SPARKLING"."SELLER" 
   (	"SELL_NO" NUMBER, 
	"USER_NO" NUMBER, 
	"BOOK_TYPE" NUMBER, 
	"PROD_TYPE" NUMBER, 
	"BOOK_SELL_NAME" VARCHAR2(100 BYTE), 
	"BOOK_COM_NAME" VARCHAR2(100 BYTE), 
	"BOOK_BUSINESS_NO" NUMBER, 
	"BOOK_SELL_ADDRESS" VARCHAR2(300 BYTE), 
	"BOOK_SELL_BANK" VARCHAR2(200 BYTE), 
	"BOOK_SELL_ACCOUNT" NUMBER, 
	"PROD_SELL_NAME" VARCHAR2(100 BYTE), 
	"PROD_COM_NAME" VARCHAR2(100 BYTE), 
	"PROD_BUSINESS_NO" NUMBER, 
	"PROD_SELL_ADDRESS" VARCHAR2(300 BYTE), 
	"PROD_SELL_BANK" VARCHAR2(200 BYTE), 
	"PROD_SELL_ACCOUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "SPARKLING"."USERS" 
   (	"USER_NO" NUMBER, 
	"USER_ID" VARCHAR2(50 BYTE), 
	"USER_NAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE), 
	"NICKNAME" VARCHAR2(30 BYTE), 
	"ADDRESS" VARCHAR2(300 BYTE), 
	"USER_PHOTO" VARCHAR2(300 BYTE), 
	"USER_PHONE" NUMBER, 
	"USER_LEVEL" NUMBER, 
	"USER_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SPARKLING.ALARM

--  DDL for Index PK_BUYPRODUCT
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPARKLING"."PK_BUYPRODUCT" ON "SPARKLING"."BUYPRODUCT" ("BUYPROD_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_PROFILE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPARKLING"."PK_PROFILE" ON "SPARKLING"."PROFILE" ("PROFILE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CART
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPARKLING"."PK_CART" ON "SPARKLING"."CART" ("CART_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ALARM
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPARKLING"."PK_ALARM" ON "SPARKLING"."ALARM" ("ALARM_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UK_USERS_NICKNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPARKLING"."UK_USERS_NICKNAME" ON "SPARKLING"."USERS" ("NICKNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_BUY
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPARKLING"."PK_BUY" ON "SPARKLING"."BUY" ("BUY_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."PRODUCT" ADD PRIMARY KEY ("PROD_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SPARKLING"."PRODUCT" MODIFY ("PROD_DATE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."PRODUCT" MODIFY ("PROD_DETAIL_IMG_SAVENAME" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."PRODUCT" MODIFY ("PROD_DETAIL_IMG_NAME" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."PRODUCT" MODIFY ("PROD_QUAL" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."PRODUCT" MODIFY ("PROD_WASH" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."PRODUCT" MODIFY ("PROD_FROM" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."PRODUCT" MODIFY ("PROD_DESC" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."PRODUCT" MODIFY ("PROD_BRAND" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."PRODUCT" MODIFY ("PROD_PRICE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."PRODUCT" MODIFY ("PROD_NAME" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."PRODUCT" MODIFY ("EVENT_CATE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."PRODUCT" MODIFY ("PROD_CATE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."PRODUCT" MODIFY ("SELL_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."USERS" ADD CONSTRAINT "UK_USERS_NICKNAME" UNIQUE ("NICKNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SPARKLING"."USERS" ADD PRIMARY KEY ("USER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SPARKLING"."USERS" MODIFY ("USER_DATE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."USERS" MODIFY ("USER_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."USERS" MODIFY ("USER_PHONE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."USERS" MODIFY ("USER_PHOTO" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."USERS" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."USERS" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."USERS" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOOKING
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."BOOKING" ADD PRIMARY KEY ("BOOKING_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SPARKLING"."BOOKING" MODIFY ("BOOKING_REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."BOOKING" MODIFY ("BOOKING_STATE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."BOOKING" MODIFY ("BOOKING_PRICE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."BOOKING" MODIFY ("BOOKING_END" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."BOOKING" MODIFY ("BOOKING_START" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."BOOKING" MODIFY ("BOOKING_DATE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."BOOKING" MODIFY ("GYM_NO" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."BOOKING" MODIFY ("BOOKING_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GYMIMG
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."GYMIMG" ADD PRIMARY KEY ("GYM_IMG_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SPARKLING"."GYMIMG" MODIFY ("GYM_IMG_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."GYMIMG" MODIFY ("GYM_IMG_NAME" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."GYMIMG" MODIFY ("GYM_IMG_SAVENAME" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."GYMIMG" MODIFY ("GYM_NO" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."GYMIMG" MODIFY ("GYM_IMG_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BUY
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."BUY" MODIFY ("BUY_NAME" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."BUY" ADD CONSTRAINT "PK_BUY" PRIMARY KEY ("BUY_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SPARKLING"."BUY" MODIFY ("BUY_STATE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."BUY" MODIFY ("BUY_PRICE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."BUY" MODIFY ("BUY_PAYTYPE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."BUY" MODIFY ("BUY_DATE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."BUY" MODIFY ("BUY_PH" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."BUY" MODIFY ("BUY_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."BUY" MODIFY ("USER_NO" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."BUY" MODIFY ("BUY_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODIMG
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."PRODIMG" ADD PRIMARY KEY ("PROD_IMG_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SPARKLING"."PRODIMG" MODIFY ("PROD_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EVENT
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."EVENT" ADD PRIMARY KEY ("EVENT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SPARKLING"."EVENT" MODIFY ("EVENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."EVENT" MODIFY ("PROFILE_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MATCHSCORE
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."MATCHSCORE" ADD PRIMARY KEY ("MATCHSCORE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SPARKLING"."MATCHSCORE" MODIFY ("B_BUY_NO" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."MATCHSCORE" MODIFY ("LOSE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."MATCHSCORE" MODIFY ("WIN" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."MATCHSCORE" MODIFY ("SCORE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."MATCHSCORE" MODIFY ("USER_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COLORSIZE
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."COLORSIZE" ADD PRIMARY KEY ("COLORSIZE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SPARKLING"."COLORSIZE" MODIFY ("STOCK" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."COLORSIZE" MODIFY ("PROD_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECORD
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."RECORD" ADD PRIMARY KEY ("RECORD_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SPARKLING"."RECORD" MODIFY ("RECORD_MATCH" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."RECORD" MODIFY ("RECORD_DATE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."RECORD" MODIFY ("RECORD_EVENT" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."RECORD" MODIFY ("RECORD_NAME" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."RECORD" MODIFY ("RECORD_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."RECORD" MODIFY ("PROFILE_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REVIEWIMG
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."REVIEWIMG" MODIFY ("REVIEW_IMG_SAVENAME" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."REVIEWIMG" MODIFY ("REVIEW_IMG_NAME" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."REVIEWIMG" MODIFY ("REVIEW_NO" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."REVIEWIMG" ADD PRIMARY KEY ("REVIEW_IMG_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SPARKLING"."REVIEWIMG" MODIFY ("REVIEW_IMG_TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ALARM
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."ALARM" ADD CONSTRAINT "PK_ALARM" PRIMARY KEY ("ALARM_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SPARKLING"."ALARM" MODIFY ("SELL_NO" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."ALARM" MODIFY ("ALARM_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."ALARM" MODIFY ("TO_USER_NO" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."ALARM" MODIFY ("FROM_USER_NO" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."ALARM" MODIFY ("ALARM_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."CART" ADD CONSTRAINT "PK_CART" PRIMARY KEY ("CART_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SPARKLING"."CART" MODIFY ("COUNT" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."CART" MODIFY ("COLORSIZE_NO" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."CART" MODIFY ("PROD_NO" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."CART" MODIFY ("CART_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SELLER
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."SELLER" ADD PRIMARY KEY ("SELL_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SPARKLING"."SELLER" MODIFY ("USER_NO" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."SELLER" MODIFY ("SELL_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GYM
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."GYM" ADD PRIMARY KEY ("GYM_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SPARKLING"."GYM" MODIFY ("GYM_DATE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."GYM" MODIFY ("GYM_EVENT" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."GYM" MODIFY ("GYM_NOTICE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."GYM" MODIFY ("GYM_TIME" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."GYM" MODIFY ("GYM_PH" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."GYM" MODIFY ("GYM_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."GYM" MODIFY ("GYM_NAME" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."GYM" MODIFY ("GYM_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."REVIEW" ADD PRIMARY KEY ("REVIEW_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SPARKLING"."REVIEW" MODIFY ("REVIEW_DATE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."REVIEW" MODIFY ("REVIEW_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."REVIEW" MODIFY ("REVIEW_TITLE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."REVIEW" MODIFY ("PROD_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BUYPRODUCT
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."BUYPRODUCT" MODIFY ("BUY_NO" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."BUYPRODUCT" ADD CONSTRAINT "PK_BUYPRODUCT" PRIMARY KEY ("BUYPROD_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SPARKLING"."BUYPRODUCT" MODIFY ("COUNT" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."BUYPRODUCT" MODIFY ("BUY_DEL_STATE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."BUYPRODUCT" MODIFY ("BUYPROD_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONVENIENCE
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."CONVENIENCE" ADD PRIMARY KEY ("CON_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SPARKLING"."CONVENIENCE" MODIFY ("CON_STATE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."CONVENIENCE" MODIFY ("CON_NAME" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."CONVENIENCE" MODIFY ("GYM_NO" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."CONVENIENCE" MODIFY ("CON_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROFILE
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."PROFILE" ADD CONSTRAINT "PK_PROFILE" PRIMARY KEY ("PROFILE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SPARKLING"."PROFILE" MODIFY ("RECENTLY_EXER" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."PROFILE" MODIFY ("PROFILE_DATE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."PROFILE" MODIFY ("EXP" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."PROFILE" MODIFY ("MAJOR" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."PROFILE" MODIFY ("CAREER" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."PROFILE" MODIFY ("WEIGHT" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."PROFILE" MODIFY ("HEIGHT" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."PROFILE" MODIFY ("USER_NO" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."PROFILE" MODIFY ("PROFILE_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QNAIMG
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."QNAIMG" ADD PRIMARY KEY ("QNA_IMG_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SPARKLING"."QNAIMG" MODIFY ("QNA_IMG_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."QNAIMG" MODIFY ("QNA_IMG_SAVENAME" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."QNAIMG" MODIFY ("QNA_IMG_NAME" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."QNAIMG" MODIFY ("QNA_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BBUY
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."BBUY" ADD PRIMARY KEY ("B_BUY_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SPARKLING"."BBUY" MODIFY ("B_BUY_PLAYER_STATE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."BBUY" MODIFY ("PROFILE_NO" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."BBUY" MODIFY ("USER_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QNA
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."QNA" ADD PRIMARY KEY ("QNA_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SPARKLING"."QNA" MODIFY ("USER_NO" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."QNA" MODIFY ("QNA_DATE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."QNA" MODIFY ("QNA_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."QNA" MODIFY ("QNA_TITLE" NOT NULL ENABLE);
  ALTER TABLE "SPARKLING"."QNA" MODIFY ("PROD_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ALARM
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."ALARM" ADD CONSTRAINT "FK_SELLER_TO_ALARM" FOREIGN KEY ("SELL_NO")
	  REFERENCES "SPARKLING"."SELLER" ("SELL_NO") ENABLE;
  ALTER TABLE "SPARKLING"."ALARM" ADD CONSTRAINT "FK_USERS_TO_ALARM" FOREIGN KEY ("TO_USER_NO")
	  REFERENCES "SPARKLING"."USERS" ("USER_NO") ENABLE;
  ALTER TABLE "SPARKLING"."ALARM" ADD CONSTRAINT "FK_USERS_TO_ALARM2" FOREIGN KEY ("FROM_USER_NO")
	  REFERENCES "SPARKLING"."USERS" ("USER_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BBUY
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."BBUY" ADD CONSTRAINT "FK_BBUY_PROFILE_NO" FOREIGN KEY ("PROFILE_NO")
	  REFERENCES "SPARKLING"."PROFILE" ("PROFILE_NO") ENABLE;
  ALTER TABLE "SPARKLING"."BBUY" ADD CONSTRAINT "FK_BBUY_USER_NO" FOREIGN KEY ("USER_NO")
	  REFERENCES "SPARKLING"."USERS" ("USER_NO") ENABLE;
  ALTER TABLE "SPARKLING"."BBUY" ADD CONSTRAINT "FK__BBUY_BOOKING_NO" FOREIGN KEY ("BOOKING_NO")
	  REFERENCES "SPARKLING"."BOOKING" ("BOOKING_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOOKING
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."BOOKING" ADD CONSTRAINT "BOOKING_FK" FOREIGN KEY ("GYM_NO")
	  REFERENCES "SPARKLING"."GYM" ("GYM_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BUY
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."BUY" ADD CONSTRAINT "FK_USERS_TO_BUY" FOREIGN KEY ("USER_NO")
	  REFERENCES "SPARKLING"."USERS" ("USER_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BUYPRODUCT
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."BUYPRODUCT" ADD CONSTRAINT "FK_BUY_TO_BUYPRODUCT" FOREIGN KEY ("BUY_NO")
	  REFERENCES "SPARKLING"."BUY" ("BUY_NO") ENABLE;
  ALTER TABLE "SPARKLING"."BUYPRODUCT" ADD CONSTRAINT "FK_COLORSIZE_TO_BUYPRODUCT" FOREIGN KEY ("COLORSIZE_NO")
	  REFERENCES "SPARKLING"."COLORSIZE" ("COLORSIZE_NO") ENABLE;
  ALTER TABLE "SPARKLING"."BUYPRODUCT" ADD CONSTRAINT "FK_PRODUCT_TO_BUYPRODUCT" FOREIGN KEY ("PROD_NO")
	  REFERENCES "SPARKLING"."PRODUCT" ("PROD_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."CART" ADD CONSTRAINT "FK_COLORSIZE_TO_CART" FOREIGN KEY ("COLORSIZE_NO")
	  REFERENCES "SPARKLING"."COLORSIZE" ("COLORSIZE_NO") ENABLE;
  ALTER TABLE "SPARKLING"."CART" ADD CONSTRAINT "FK_PRODUCT_TO_CART" FOREIGN KEY ("PROD_NO")
	  REFERENCES "SPARKLING"."PRODUCT" ("PROD_NO") ENABLE;
  ALTER TABLE "SPARKLING"."CART" ADD CONSTRAINT "FK_USERS_TO_CART" FOREIGN KEY ("USER_NO")
	  REFERENCES "SPARKLING"."USERS" ("USER_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COLORSIZE
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."COLORSIZE" ADD CONSTRAINT "C_COLORSIZE_FK" FOREIGN KEY ("PROD_NO")
	  REFERENCES "SPARKLING"."PRODUCT" ("PROD_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONVENIENCE
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."CONVENIENCE" ADD CONSTRAINT "CON_FK" FOREIGN KEY ("GYM_NO")
	  REFERENCES "SPARKLING"."GYM" ("GYM_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EVENT
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."EVENT" ADD CONSTRAINT "FK_EVENT_PROFILE_NO" FOREIGN KEY ("PROFILE_NO")
	  REFERENCES "SPARKLING"."PROFILE" ("PROFILE_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GYM
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."GYM" ADD CONSTRAINT "GYM_FK_SELL_NO" FOREIGN KEY ("SELL_NO")
	  REFERENCES "SPARKLING"."SELLER" ("SELL_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GYMIMG
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."GYMIMG" ADD CONSTRAINT "GIMG_FK" FOREIGN KEY ("GYM_NO")
	  REFERENCES "SPARKLING"."GYM" ("GYM_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MATCHSCORE
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."MATCHSCORE" ADD CONSTRAINT "FK_MATCHSCORE_B_BUY_NO" FOREIGN KEY ("B_BUY_NO")
	  REFERENCES "SPARKLING"."BBUY" ("B_BUY_NO") ENABLE;
  ALTER TABLE "SPARKLING"."MATCHSCORE" ADD CONSTRAINT "FK_MATCHSCORE_USER_NO" FOREIGN KEY ("USER_NO")
	  REFERENCES "SPARKLING"."USERS" ("USER_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODIMG
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."PRODIMG" ADD CONSTRAINT "C_PRODIMG_FK" FOREIGN KEY ("PROD_NO")
	  REFERENCES "SPARKLING"."PRODUCT" ("PROD_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."PRODUCT" ADD CONSTRAINT "FK_PRODUCT_SELL_NO" FOREIGN KEY ("SELL_NO")
	  REFERENCES "SPARKLING"."SELLER" ("SELL_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QNA
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."QNA" ADD CONSTRAINT "C_QNA_PRODNO_FK" FOREIGN KEY ("PROD_NO")
	  REFERENCES "SPARKLING"."PRODUCT" ("PROD_NO") ENABLE;
  ALTER TABLE "SPARKLING"."QNA" ADD CONSTRAINT "C_QNA_USERNO_FK" FOREIGN KEY ("USER_NO")
	  REFERENCES "SPARKLING"."USERS" ("USER_NO") ENABLE;
  ALTER TABLE "SPARKLING"."QNA" ADD CONSTRAINT "FK_BUY_TO_QNA" FOREIGN KEY ("BUY_NO")
	  REFERENCES "SPARKLING"."BUY" ("BUY_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QNAIMG
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."QNAIMG" ADD CONSTRAINT "C_QNAIMG_FK" FOREIGN KEY ("QNA_NO")
	  REFERENCES "SPARKLING"."QNA" ("QNA_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECORD
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."RECORD" ADD CONSTRAINT "FK_RECORD_PROFILE_NO" FOREIGN KEY ("PROFILE_NO")
	  REFERENCES "SPARKLING"."PROFILE" ("PROFILE_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."REVIEW" ADD CONSTRAINT "C_REVIEW_PRODNO_FK" FOREIGN KEY ("PROD_NO")
	  REFERENCES "SPARKLING"."PRODUCT" ("PROD_NO") ENABLE;
  ALTER TABLE "SPARKLING"."REVIEW" ADD CONSTRAINT "FK_BUY_TO_REVIEW" FOREIGN KEY ("BUY_NO")
	  REFERENCES "SPARKLING"."BUY" ("BUY_NO") ENABLE;
  ALTER TABLE "SPARKLING"."REVIEW" ADD CONSTRAINT "FK_USERS_TO_REVIEW" FOREIGN KEY ("USER_NO")
	  REFERENCES "SPARKLING"."USERS" ("USER_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVIEWIMG
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."REVIEWIMG" ADD CONSTRAINT "C_REVIEWIMG_FK" FOREIGN KEY ("REVIEW_NO")
	  REFERENCES "SPARKLING"."REVIEW" ("REVIEW_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SELLER
--------------------------------------------------------

  ALTER TABLE "SPARKLING"."SELLER" ADD CONSTRAINT "SELLER_FK" FOREIGN KEY ("USER_NO")
	  REFERENCES "SPARKLING"."USERS" ("USER_NO") ENABLE;
